name: Check Deno Code Validity

# This section defines when the workflow runs
on:
  # 1. This keeps the original behavior: run automatically on every push to main
  push:
    branches:
      - main
  
  # 2. This is the new line that adds the manual trigger
  workflow_dispatch:

jobs:
  check:
    # This job will run on a temporary virtual machine
    runs-on: ubuntu-latest

    steps:
      # Step 1: Check out your repository's code
      - name: Checkout repository
        uses: actions/checkout@v4

      # Step 2: Set up the Deno environment
      - name: Setup Deno
        uses: deno-land/setup-deno@v1
        with:
          deno-version: v1.x # Use the latest stable version

      # Step 3: Check the code for any Deno-specific errors
      # This command understands all of Deno's features.
      - name: Verify Deno code
        run: deno lint

      # You can also add a type-checking step
      - name: Type-check the code
        run: deno check main.ts